### ISSUE TITLE
Demo执行失败

### ISSUE THREAD

**Issue by xuyisheng** [GalvinChen/IncrementalCoverage#1]
* What went wrong:
Some problems were found with the configuration of task ':app:generateCoverageReport' (type 'CodeCoverageReportTask').
> No value has been specified for property 'classesDirectory'.
> No value has been specified for property 'executionDataFile'.
> No value has been specified for property 'reportDirectory'.

请问是需要配置这些参数吗

**Comment by GalvinChen** [comment]
在 local.properties 里配置 baseline=HEAD~3 是可以的，默认的 HEAD~1 获取不到任何 diff 代码，所以任务 :app:generateCoverageReport 没有任何输入。项目还不完整，有很多小瑕疵，不过核心功能增量代码覆盖率是可以工作的。

**Comment by xuyisheng** [comment]
> 在 local.properties 里配置 baseline=HEAD~3 是可以的，默认的 HEAD~1 获取不到任何 diff 代码，所以任务 :app:generateCoverageReport 没有任何输入。项目还不完整，有很多小瑕疵，不过核心功能增量代码覆盖率是可以工作的。

方便加下微信吗 我的微信 13641719651 可以一起探讨下
